import type { Metadata } from "next";

import "./globals.css";
import { general } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={general.className}>{children}</body>
    </html>
  );
}
