// Generated by https://quicktype.io

export interface ColorTypes {
  [key: string]: string;
}

export interface Species {
  name: keyof ColorTypes;
  url: string;
}

export interface Type {
  slot: number;
  type: Species;
}
